### PR TITLE
add support for file path and BytesIO as inputs

### PR DESCRIPTION
**Pull request by vierofernando**
- removed unused imports
- improved exception classes
- improved `Upload` class
- changed the usage from `await <object>.upload(('png', bytes))` to `await <object>.upload(bytes, file_format='png')` 
- added support for `io.BytesIO` and file path as inputs for `<object>.upload` function
- pushed to version `v1.0.3`

### CODE REVIEW

**Review by Fxcilities — CHANGES_REQUESTED** [review]
Unexpected "U"

**Comment by Fxcilities** [comment]
wrong mf button

**Review by Fxcilities — CHANGES_REQUESTED** [review]
few changes but nice commit in all

**Comment by Fxcilities** [comment]
i hate mobile github istg

**Comment by Fxcilities** [comment]
i guess il just merge and then commit normally but thanks for the pr

**Comment by vierofernando** [comment]
yw

**Pull request merged**
